version: "3.4"

services:
  clip-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        COMPUTE: cpu # cpu, cuda
    image: clip-api
    ports:
      - 5000:5000
    container_name: clip-api
    environment:
      - GUNICORN_CMD_ARGS="--keep-alive 0"
      - CLIP_MODEL=ViT-B/32 #B/32, L/14
      - TESSDATA_PREFIX=/code/app/tessdata
    volumes:
      - ./api/app:/code/app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 5000 --app-dir app"
